name: PR Labeler
on:
  pull_request:
    types: [opened, synchronize, reopened] 
jobs:
  label_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Apply labels based on file changes
        uses: actions/labeler@v5
        with:
          repo-token: $ {{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml 
