name: Basic CI Pipeline

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Simple Print Command
        run: |
          echo "CI Running"
          echo "This is my log content" > build.log

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: CI-Build-Artifact
          path: build.log
